=== joncampbell123/windows_sdk_collection/win/platform-sdk/2000-04/installed/Help/Inet.chm.html/xml/archive/xml-europe-99/invoice.dtd
<!-- this is a DTD for an XML BNF format -->

<!ELEMENT Data (Invoice | Products )*> 

<!ELEMENT Invoice (Item | Address)*>			
<!ATTLIST Invoice
	id	ID	#REQUIRED 
    	name CDATA #IMPLIED
	billto	IDREF	#IMPLIED
	shipto	IDREF	#IMPLIED
	amount	CDATA	#IMPLIED
    	items IDREFS #IMPLIED >
		
<!ELEMENT Address ANY>
<!ATTLIST Address
	id	ID	#REQUIRED 
	name	CDATA	#IMPLIED
	street	CDATA	#IMPLIED
	city	CDATA	#IMPLIED
	state	CDATA	#IMPLIED
	phone	CDATA	#IMPLIED >
	
<!ELEMENT Item ANY>		
<!ATTLIST Item
	id	ID	#REQUIRED 
	quantity	CDATA	#IMPLIED
	price		CDATA	#IMPLIED
	product		IDREF	#IMPLIED >

<!ELEMENT Products (Product)+>			
<!ELEMENT Product ANY>		
<!ATTLIST Product
	id	ID	#REQUIRED 
	company	CDATA	#IMPLIED
	name	CDATA	#IMPLIED
	price	CDATA	#IMPLIED
	>

=== joncampbell123/windows_sdk_collection/win/platform-sdk/2000-04/setup/common/help/inet.chm.html/xml/archive/xml-europe-99/invoice2.xml
<?xml-stylesheet type="text/xsl" href="invoice.xsl"?>

<!DOCTYPE Data SYSTEM "invoice.dtd" >

<Data>
<Invoice id="invoice:1" shipto="addr:1" billto="addr:2" amount="1460.00"
	items="item:1 item:2 item:3 item:4 item:5" >
	<Address id="addr:1" 
		name="Adam Bosworth" street="1234 56th St" city="Mercer Island"
			state="Washington" phone="(425) 936-5920" />
	<Address id="addr:2"
		name="Microsoft" street="1 Microsoft Way" city="Redmond" 
			state="Washington" phone="(425) 882 8080" />
	<Item id="item:1" quantity="10" price="250.00" product="product:1" />
	<Item id="item:2" quantity="8"  price="450.00" product="product:5" />
	<Item id="item:3" quantity="6"  price="59.00" product="product:4" />
	<Item id="item:4" quantity="4"  price="99.00" product="product:3" />
	<Item id="item:5" quantity="2"  price="79.00" product="product:2" />
</Invoice>

<Products>
	<Product id="product:1" company="Microsoft" name="Office 2000" price="250.00"/>
	<Product id="product:2" company="Microsoft" name="IE 5.0" price="79.00"/>
	<Product id="product:3" company="Microsoft" name="Windows 98" price="99.00"/>
	<Product id="product:4" company="Microsoft" name="Encarta" price="59.00"/>
	<Product id="product:5" company="Microsoft" name="Sql Server" price="450.00"/>
</Products>
</Data>
