=== joncampbell123/windows_sdk_collection/win/platform-sdk/2000-04/setup/common/help/inet.chm.html/xml/archive/xml-europe-99/classes2.dtd
<!-- this is a DTD for an XML BNF format -->

<!ELEMENT Data (StudentBody | Faculty | ClassList | Departments | Workgroups)*> 

<!ELEMENT StudentBody (Student)*>			
<!ELEMENT Student ANY>			
<!ATTLIST Student
	id	ID	#REQUIRED 
    name CDATA #IMPLIED
    attends IDREFS #IMPLIED >

<!ELEMENT Faculty (Teacher)*>			
<!ELEMENT Teacher ANY>		
<!ATTLIST Teacher
	id	ID	#REQUIRED 
    name CDATA #IMPLIED
    teaches IDREFS #IMPLIED >

<!ELEMENT ClassList (Class)*>			
<!ELEMENT Class (Assignment)*>		
<!ATTLIST Class
	id	ID	#REQUIRED 
    name CDATA #IMPLIED
    dept IDREF #IMPLIED
    taughtBy IDREF #IMPLIED 
    attendedBy IDREFS #IMPLIED>

<!ELEMENT Departments (Dept)*>			
<!ELEMENT Dept ANY>		
<!ATTLIST Dept
	id	ID	#REQUIRED 
    name CDATA #IMPLIED>

<!ELEMENT Assignment (p|Assignment)+>
<!ATTLIST Assignment	
	date	CDATA	#IMPLIED
	workgroup IDREFS #IMPLIED>

<!ELEMENT p (#PCDATA|Profref)*>
<!ELEMENT Profref (#PCDATA)>
<!ATTLIST Profref dueto IDREF #IMPLIED>

<!ELEMENT Workgroups (Workgroup)*>	
<!ELEMENT Workgroup ANY>
<!ATTLIST Workgroup
	id	ID	#REQUIRED 
	name	CDATA	#IMPLIED
	leader	IDREF	#IMPLIED
	group	IDREFS	#IMPLIED>

=== joncampbell123/windows_sdk_collection/win/platform-sdk/2000-04/setup/common/help/inet.chm.html/xml/archive/xml-europe-99/classes2.xml
<?xml-stylesheet type="text/xsl" ?>
<!DOCTYPE Data SYSTEM "classes2.dtd" >

<Data>
  <StudentBody>
    <Student id="s1" name="Adam"     attends="c1 c3 c6"  />
    <Student id="s2" name="David"    attends="c2 c4" />
    <Student id="s3" name="Istvan"   attends="c2 c4 c6" />
    <Student id="s4" name="Simon"    attends="c1 c3 c5" />
    <Student id="s5" name="William"  attends="c1 c3 c5 c6" />
    <Student id="s6" name="Scott" />
  </StudentBody>
  <Faculty>
    <Teacher id="t1" name="Sam"   teaches="c1 c3 c4" />
    <Teacher id="t2" name="Chris" teaches="c2 c3 c5" />
	  <Teacher id="t3" name="Bill"  teaches="c5 c6" />
    <Teacher id="t4" name="Justin" />
  </Faculty>
  <ClassList>
    <Class id="c1" name="Intro to Programming" dept="d1" taughtBy="t1" attendedBy="s1 s4 s5">
      <Assignment date="1999 1/13" workgroup="w1">
        <p>Study all the relevant material written by <Profref dueto="t1">Sam</Profref></p>
        <p>Then write a paper summarizing the material and get it reviewed by <Profref dueto="s6">Stanford guy</Profref></p>
      </Assignment>
      <Assignment date="1999 4/23" workgroup="t3 s2 s4 t2">
        <p>You have an informal workgroup for this. <Profref dueto="t3">Bill</Profref> is your leader</p>
        <p>When you have finished this assignment, hand it in to any teacher for this class</p>
      </Assignment>
      <Assignment date="1999 5/28" workgroup="w1">
        <p>Work with your workgroup for this assignment to write this assignment</p>
        <p>Get it reviewed by the leader of your workgroup</p>
      </Assignment>
    </Class> 
    <Class id="c2" name = "Databases" dept="d1" taughtBy="t2" attendedBy="s2 s3" />
    <Class id="c3" name="Operating Systems" dept="d1" taughtBy="t2" attendedBy="s1 s4 s5" />
    <Class id="c4" name="Networks" dept="d1" taughtBy="t1" attendedBy="s2 s3">
      <Assignment date="2000 2/24" workgroup="w1">
        <p>Study all the relevant material written by <Profref dueto="t4"/></p>
        <p>Then write a paper summarizing the material and get it reviewed by <Profref dueto="s6"/></p>
        <Assignment date="1999 H2" workgroup="w1">
          <p>Research comments by<Profref dueto="s6"/></p>
          <p>Research rebuttal by <Profref dueto="t3"/></p>
        </Assignment>
      </Assignment>
    </Class>
    <Class id="c5" name="Algorithms and Graphs" dept="d1" taughtBy="t2" attendedBy= "s1 s4 s5"/>
    <Class id="c6" name="Power and Pragmatism" dept="d2" taughtBy="t3" attendedBy="s1 s3 s5">
      <Assignment date="2001">
        <p>Study all the relevant material written by <Profref dueto="t4">you know who</Profref></p>
        <p>Write a brief summarizing the material</p>
        <p>Get it reviewed by <Profref dueto="s1">the dude</Profref></p>
      </Assignment>
      <Assignment date="2000" workgroup="w1">
        <p>Discuss the true nature of innovation</p>
        <p>Pay special attention to innovation in semi structured data processing</p>
        <p>Get feedback from the workgroup: <Profref dueto="w1"/></p>
      </Assignment>
    </Class>
  </ClassList>
  <Departments>
    <Dept id="d1" name="Computer Science" />
    <Dept id="d2" name="Real Life" />
  </Departments>
  <Workgroups>
    <Workgroup id="w1" name="Chris's group" leader="t2" group="t2 s1 s3 s5"/>
  </Workgroups>
</Data>
